stages:
  - lint
  - test

image: python:3.9.2-buster

.only: &only
  only:
    - master
    - merge_requests

lint-style:
  stage: lint
  script: |
    pip install isort black flake8 pycodestyle
    isort --check .
    black --check .
    flake8 .
    pycodestyle .
  <<: *only

lint-types:
  stage: lint
  script: |
    pip install mypy
    mypy .
  <<: *only

test:
  stage: test
  script: |
    pip install poetry
    poetry config virtualenvs.create false
    poetry install --no-root
    pytest --cov .
  <<: *only
